spring:
#  redis数据库配置
  data:
    redis:
#      链接数据库
      host: localhost
#      端口
      port: 6379
      password: 123456789
#      几号数据库，一共16个
      database: 3
  application:
    name: dining_manage
  #mysql连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dining_db
    username: root
    password: 5678
  servlet:
    multipart:
      #      最大单个文件大小
      max-file-size: 1024MB
      #      最大请求文件大小
      max-request-size: 1024MB
#      ollama大模型
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b

mybatis:
  configuration:
    #驼峰命名
    map-underscore-to-camel-case: true
    #    显示sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-date
    region: cn-beijing











